# Generated by Django 3.1.2 on 2020-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2', '0005_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=100)),
                ('exercise_rep', models.CharField(max_length=100)),
                ('calories_burnt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('total_calories', models.CharField(max_length=100)),
            ],
        ),
    ]
